resources:
- SpinnakerService.yml

# Apply the patches top down order
patches:
- path: config-patch.yml
  target:
    version: v1alpha2
    kind: SpinnakerService
- path: profiles-patch.yml
  target:
    version: v1alpha2
    kind: SpinnakerService
- path: files-patch.yml
  target:
    version: v1alpha2
    kind: SpinnakerService
- path: service-settings-patch.yml
  target:
    version: v1alpha2
    kind: SpinnakerService
