queue_rules:
  - name: duplicated default from Automatically merge into master after build and
      review
    queue_conditions:
      - base=master
      - status-success=main
      - "#approved-reviews-by>=1"
    merge_conditions:
      - status-success=main
    merge_method: squash
  - name: duplicated default from Automatically merge into release- after build and
      approval
    queue_conditions:
      - base~=^release-
      - status-success=main
      - "#approved-reviews-by>=1"
    merge_conditions:
      - status-success=main
    merge_method: squash
  - name: duplicated default from Automatically merge backport into release branches
    queue_conditions:
      - head~=mergify/bp
      - author~=mergify
      - base~=^release-
      - status-success=main
    merge_conditions:
      - status-success=main
    merge_method: squash
  - name: duplicated default from Automatically mergify-yaml changes to master
    queue_conditions:
      - base=master
      - title~=^fix(mergify)
    merge_conditions:
      - status-success=main
    merge_method: squash

pull_request_rules:
  - name: Automatically merge into master after build and review
    conditions:
      - base=master
      - status-success=main
      - "#approved-reviews-by>=1"
    actions:
      label:
        add: ["auto merged"]
  - name: Automatically merge into release- after build and approval
    conditions:
      - base~=^release-
      - status-success=main
      - "#approved-reviews-by>=1"
    actions:
      label:
        add: ["auto merged"]
  - name: Automatically merge backport into release branches
    conditions:
      - head~=mergify/bp
      - author~=mergify
      - base~=^release-
      - status-success=main
    actions:
      label:
        add: ["auto merged"]
  - name: Automatically mergify-yaml changes to master
    conditions:
      - base=master
      - title~=^fix(mergify)
    actions:
      label:
        add: ["auto merged"]
  - name: Automatically merge backport into release branches + Automatically merge
      into master after build and review + Automatically merge into release- after
      build and approval + Automatically mergify-yaml changes to master
    conditions: []
    actions:
      queue:
