queue_rules:
  - name: default
    conditions:
      - status-success=main

pull_request_rules:
  - name: Automatically merge into master after build and review
    conditions:
      - base=master
      - status-success=main
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge into release- after build and approval
    conditions:
      - base~=^release-
      - status-success=main
      - "#approved-reviews-by>=1"
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically merge backport into release branches
    conditions:
      - head~=mergify/bp
      - author~=mergify
      - base~=^release-
      - status-success=main
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
  - name: Automatically mergify-yaml changes to master
    conditions:
      - base=master
      - title~=^fix(mergify)
    actions:
      queue:
        method: squash
        name: default
      label:
        add: ["auto merged"]
