apiVersion: v1
kind: ConfigMap
metadata:
  name: spinconfig-v002
data:
  config: |
    name: default
    version: 1.15.1
    providers:
      appengine:
        enabled: false
        accounts: []
      aws:
        enabled: false
        accounts: []
        bakeryDefaults:
          baseImages: []
        defaultKeyPairTemplate: '{{name}}-keypair'
        defaultRegions:
        - name: us-west-2
        defaults:
          iamRole: BaseIAMRole
      ecs:
        enabled: false
        accounts: []
      azure:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: azure-linux.json
          baseImages: []
      dcos:
        enabled: false
        accounts: []
        clusters: []
      dockerRegistry:
        enabled: false
        accounts: []
      google:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: gce.json
          baseImages: []
          zone: us-central1-f
          network: default
          useInternalIp: false
      kubernetes:
        enabled: true
        accounts:
        - name: kubernetes
          requiredGroupMembership: []
          providerVersion: V2
          permissions: {}
          dockerRegistries: []
          configureImagePullSecrets: true
          cacheThreads: 1
          omitNamespaces: []
          kinds: []
          omitKinds: []
          customResources: []
          cachingPolicies: []
          serviceAccount: true
          oAuthScopes: []
          onlySpinnakerManaged: false
        primaryAccount: kubernetes
      openstack:
        enabled: false
        accounts: []
        bakeryDefaults:
          baseImages: []
      oracle:
        enabled: false
        accounts: []
        bakeryDefaults:
          templateFile: oci.json
          baseImages: []
      cloudfoundry:
        enabled: false
        accounts: []
    deploymentEnvironment:
      size: SMALL
      type: Distributed
      accountName: kubernetes
      updateVersions: true
      consul:
        enabled: false
      vault:
        enabled: false
      customSizing: {}
      sidecars: {}
      initContainers: {}
      hostAliases: {}
      affinity: {}
      nodeSelectors: {}
      gitConfig:
        upstreamUser: spinnaker
      haServices:
        clouddriver:
          enabled: false
          disableClouddriverRoDeck: false
        echo:
          enabled: false
    persistentStorage:
      persistentStoreType: s3
      azs: {}
      gcs:
        rootFolder: front50
      redis: {}
      s3:
        bucket: mybucket
        rootFolder: front50
        region: us-west-2
      oracle: {}
    features:
      auth: false
      fiat: false
      chaos: false
      entityTags: false
      jobs: false
      artifacts: true
    metricStores:
      datadog:
        enabled: false
        tags: []
      prometheus:
        enabled: false
        add_source_metalabels: true
      stackdriver:
        enabled: false
      period: 30
      enabled: false
    notifications:
      slack:
        enabled: false
      twilio:
        enabled: false
        baseUrl: https://api.twilio.com/
    timezone: America/Los_Angeles
    ci:
      jenkins:
        enabled: false
        masters: []
      travis:
        enabled: false
        masters: []
      wercker:
        enabled: false
        masters: []
    security:
      apiSecurity:
        ssl:
          enabled: false
      uiSecurity:
        ssl:
          enabled: false
      authn:
        oauth2:
          enabled: false
          client: {}
          resource: {}
          userInfoMapping: {}
        saml:
          enabled: false
          userAttributeMapping: {}
        ldap:
          enabled: false
        x509:
          enabled: false
        iap:
          enabled: false
        enabled: false
      authz:
        groupMembership:
          service: EXTERNAL
          google:
            roleProviderType: GOOGLE
          github:
            roleProviderType: GITHUB
          file:
            roleProviderType: FILE
          ldap:
            roleProviderType: LDAP
        enabled: false
    artifacts:
      bitbucket:
        enabled: false
        accounts: []
      gcs:
        enabled: false
        accounts: []
      oracle:
        enabled: false
        accounts: []
      github:
        enabled: false
        accounts: []
      gitlab:
        enabled: false
        accounts: []
      http:
        enabled: false
        accounts: []
      helm:
        enabled: false
        accounts: []
      s3:
        enabled: false
        accounts: []
      maven:
        enabled: false
        accounts: []
      templates: []
    pubsub:
      enabled: false
      google:
        enabled: false
        pubsubType: GOOGLE
        subscriptions: []
        publishers: []
    canary:
      enabled: false
      serviceIntegrations:
      - name: google
        enabled: false
        accounts: []
        gcsEnabled: false
        stackdriverEnabled: false
      - name: prometheus
        enabled: false
        accounts: []
      - name: datadog
        enabled: false
        accounts: []
      - name: signalfx
        enabled: false
        accounts: []
      - name: aws
        enabled: false
        accounts: []
        s3Enabled: false
      reduxLoggerEnabled: true
      defaultJudge: NetflixACAJudge-v1.0
      stagesEnabled: true
      templatesEnabled: true
      showAllConfigsEnabled: true
    webhook:
      trust:
        enabled: false
