FROM golang:1.13.8-alpine3.11

# Must be one of: "snapshot", "rc" or "release"
ARG VERSION_TYPE=snapshot

# vendor flags conflict with `go get`
# so we fetch golint before running make
# and setting the env variable
RUN apk update && apk add git make bash build-base gcc bc
RUN go get -u golang.org/x/lint/golint

ENV GO111MODULE=on GOOS=linux GOARCH=amd64
WORKDIR /opt/spinnaker-operator/build/
ADD ./ /opt/spinnaker-operator/build/
RUN make build VERSION_TYPE=${VERSION_TYPE} OS=linux ARCH=amd64
