apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
  name: spinnakeraccounts.spinnaker.io
spec:
  additionalPrinterColumns:
    - JSONPath: .spec.type
      description: Type
      name: type
      type: string
  group: spinnaker.io
  names:
    kind: SpinnakerAccount
    listKind: SpinnakerAccountList
    plural: spinnakeraccounts
    singular: spinnakeraccount
    shortNames:
      - spinaccount
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            enabled:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            permissions:
              additionalProperties:
                items:
                  type: string
                type: array
              type: object
            type:
              type: string
            validate:
              type: boolean
          required:
          - enabled
          - type
          - validate
          - permissions
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
