// Code generated by MockGen. DO NOT EDIT.
// Source: docker_validator.go

// Package validate is a generated GoMock package.
package validate

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockdockerRepoValidator is a mock of dockerRepoValidator interface
type MockdockerRepoValidator struct {
	ctrl     *gomock.Controller
	recorder *MockdockerRepoValidatorMockRecorder
}

// MockdockerRepoValidatorMockRecorder is the mock recorder for MockdockerRepoValidator
type MockdockerRepoValidatorMockRecorder struct {
	mock *MockdockerRepoValidator
}

// NewMockdockerRepoValidator creates a new mock instance
func NewMockdockerRepoValidator(ctrl *gomock.Controller) *MockdockerRepoValidator {
	mock := &MockdockerRepoValidator{ctrl: ctrl}
	mock.recorder = &MockdockerRepoValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockdockerRepoValidator) EXPECT() *MockdockerRepoValidatorMockRecorder {
	return m.recorder
}

// repository mocks base method
func (m *MockdockerRepoValidator) repository(registry dockerRegistryAccount, service dockerRegistryService) []error {
	ret := m.ctrl.Call(m, "repository", registry, service)
	ret0, _ := ret[0].([]error)
	return ret0
}

// repository indicates an expected call of repository
func (mr *MockdockerRepoValidatorMockRecorder) repository(registry, service interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "repository", reflect.TypeOf((*MockdockerRepoValidator)(nil).repository), registry, service)
}

// imageTags mocks base method
func (m *MockdockerRepoValidator) imageTags(repository string, service *dockerRegistryService) error {
	ret := m.ctrl.Call(m, "imageTags", repository, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// imageTags indicates an expected call of imageTags
func (mr *MockdockerRepoValidatorMockRecorder) imageTags(repository, service interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "imageTags", reflect.TypeOf((*MockdockerRepoValidator)(nil).imageTags), repository, service)
}
