// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package interfaces

import (
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{}
}
