name: spinnaker-operator
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch full history
        run: git fetch --prune --tags --unshallow

      - name: Login to Dockerhub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p "${{ secrets.DOCKERHUB_PASSWORD }}" docker.io

      - name: Determine build type
        id: build_type
        run: |
          echo "github.ref: ${{ github.ref }}"
          if [[ ${{ github.ref }} = "refs/heads/master" ]]
          then
            echo "Building release candidate"
            echo "##[set-output name=build_type;]rc"
            echo "##[set-output name=make_args;]VERSION_TYPE=rc REGISTRY=docker.io REGISTRY_ORG=armory"
          elif [[ ${{ github.ref }} =~ ^refs/heads/release-* ]]
          then
            echo "Building final release"
            echo "##[set-output name=build_type;]release"
            echo "##[set-output name=make_args;]VERSION_TYPE=release REGISTRY=docker.io REGISTRY_ORG=armory"
          else
            echo "Building snapshot"
            echo "##[set-output name=build_type;]snapshot"
            echo "##[set-output name=make_args;]VERSION_TYPE=snapshot REGISTRY=armory-docker-local.jfrog.io REGISTRY_ORG=armory"
          fi

      - name: Build
        run: |
          make docker-build ${{ steps.build_type.outputs.make_args }}

      - name: Unit tests
        run: |
          make docker-test ${{ steps.build_type.outputs.make_args }}

      - name: Package
        run: |
          make docker-package ${{ steps.build_type.outputs.make_args }}

      - name: Push
        run: |
          make docker-push ${{ steps.build_type.outputs.make_args }}
